name: "Azure Blob Storage File Upload"
author: "Ymoona"
description: "Uploads a file to Azure Blob Storage"
branding:
  icon: "box"
  color: "green"
inputs:
  connection_string:
    description: "The connection string for the storage account. Used if value is set. Either connection_string or sas_token must be supplied"
    required: true
  container_name:
    description: "The name of the storage account container the file will be uploaded to"
    required: true
  source_dir:
    description: "The name of the directory you want to upload the file from"
    required: true
  file: 
    description: "The name of the file to upload"
    required: true 
  overwrite:
    description: "Overwrite existing files in the destination container. Defaults to false"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
